services:
  giveaway:
    build: .
    container_name: giveaway
    command: sh -c "
      migrate -path ./migrations -database 'postgres://postgres:password@postgres-giveaway:5432/postgres?sslmode=disable' up &&
      ./main
      "
    depends_on:
      postgres-giveaway:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - giveaway-network

  postgres-giveaway:
    image: "postgres:latest"
    container_name: postgres-giveaway
    restart: unless-stopped
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - giveaway-network

networks:
  giveaway-network:
    driver: bridge
